export * from './Home'
export * from './Contact'
export * from './Navbar'
export * from './About'
export * from './Collection'
export * from './Gallery'
export * from './SignIn'
export * from './Footer'